/* MODIFICARE ESERCIZIO 2 IN MODO CHE PRENDA L'INPUT DAL FILE "TESTFILE" E SCRIVA L'OUTPUT NEL FILE "OUTPUTFIL"
	UTILIZZARE LE FUNZIONI PER LA DUPLICAZIONE DEI FILE DESCRIPTOR
	- TUTTE LE READ ..
*/

#define BUFFSIZE 15
int main(){
	char op1[BUFFSIZE], char op2[BUFFSIZE], char output[BUFFSIZE];
	int fd, fd2;
	
	fd 0
}
